# Commodities

In [2]:
import requests
import pandas as pd
import os

# USDA API Key
USDA_API_KEY = os.getenv("USDA_API_KEY")

# Base URL
BASE_URL = "https://api.fas.usda.gov"

# Parameters for request
params = {"api_key": USDA_API_KEY}
ENDPOINT = f"/api/esr/commodities"

response = requests.get(BASE_URL + ENDPOINT, params=params)

if response.status_code == 200:
    data = response.json()
    df = pd.DataFrame(data)
    commodities = pd.concat(
        [
            df[df["commodityName"].str.contains("corn", case=False)],
            df[df["commodityName"].str.contains("soybean", case=False)],
            df[df["commodityName"].str.contains("wheat", case=False)]
        ],
        ignore_index=True,
    )
else:
    print(f"Error: {response.status_code}, {response.text}")

commodities

    commodityCode        commodityName  unitId
0             401                 Corn       1
1             801             Soybeans       1
2             901  Soybean cake & meal       1
3             902          Soybean Oil       1
4             101          Wheat - HRW       1
5             102          Wheat - SRW       1
6             103          Wheat - HRS       1
7             104        Wheat - White       1
8             105        Wheat - Durum       1
9             106        Wheat - Mixed       1
10            107            All Wheat       1
11            201       Wheat Products       1

# Countries

In [9]:
ENDPOINT = f"/api/esr/countries"
response = requests.get(BASE_URL + ENDPOINT, params=params)

if response.status_code == 200:
    data = response.json()
    df = pd.DataFrame(data)
    countries = pd.concat(
        [
            df[df["countryDescription"].str.contains("mexico", case=False)],
            df[df["countryDescription"].str.contains("japan", case=False)],
            df[df["countryDescription"].str.contains("korea, republic", case=False)], # South Korea
            df[df["countryDescription"].str.contains("colombia", case=False)],
            df[df["countryDescription"].str.contains("european union", case=False)],
            df[df["countryDescription"].str.contains("taiwan", case=False)],
            df[df["countryDescription"].str.contains("guatemala", case=False)],
            df[df["countryDescription"].str.contains("vietnam", case=False) & ~df["countryDescription"].str.contains("south", case=False)],
            df[df["countryDescription"].str.contains("canada", case=False)],
            df[df["countryDescription"].str.contains("honduras", case=False)],
            df[df["countryDescription"].str.contains("philippines", case=False)],
            df[df["countryDescription"].str.contains("nigeria", case=False)],
            df[df["countryDescription"].str.contains("indonesia", case=False)],
            df[df["countryDescription"].str.contains("thailand", case=False)],
            df[df["countryDescription"].str.contains("china", case=False)],
            df[df["countryDescription"].str.contains("egypt", case=False)],
            df[df["countryDescription"].str.contains("pakistan", case=False)],
            df[df["countryDescription"].str.contains("bangladesh", case=False)]
        ],
        ignore_index=True,
    )
else:
    print(f"Error: {response.status_code}, {response.text}")

countries

,countryCode,countryName,countryDescription,regionId,gencCode
0,2010,MEXICO,MEXICO,11,MEX
1,5880,JAPAN,JAPAN,5,JPN
2,5800,KOR REP,"KOREA, REPUBLIC OF",9,None
3,3010,COLOMB,COLOMBIA,11,COL
4,1,EUROPEAN,EUROPEAN UNION - 27,1,None
5,5830,TAIWAN,TAIWAN,6,TWN
6,2050,GUATMAL,GUATEMALA,11,GTM
7,5520,VIETNAM,VIETNAM,9,VNM
8,1220,CANADA,CANADA,11,CAN
9,2150,HONDURA,HONDURAS,11,HND
10,5650,PHIL,PHILIPPINES,9,PHL
11,7530,NIGERIA,NIGERIA,10,NGA
12,5600,INDNSIA,INDONESIA,9,IDN
13,5490,THAILND,THAILAND,9,THA
14,5700,CHINA,"CHINA, PEOPLES REPUBLIC OF",7,CHN
15,7290,EGYPT,EGYPT,10,EGY
16,5350,PAKISTN,PAKISTAN,9,PAK
17,5380,BANGLADH,BANGLADESH,9,BGD

# Units

In [18]:
unit_ids = [1] # From selected commodities

ENDPOINT = f"/api/esr/unitsOfMeasure"
response = requests.get(BASE_URL + ENDPOINT, params=params)

if response.status_code == 200:
    data = response.json()
    df = pd.DataFrame(data)
    units = df[df["unitId"].isin(unit_ids)]
else:
    print(f"Error: {response.status_code}, {response.text}")

units

   unitId    unitNames
0       1  Metric Tons